{% set name = "powerplantmatching" %}
{% set version = "0.5.17" %}
{% set sha256 = "3252b0dc7fa103f2f51e1a898f8012cd17898573ef14c0b0951f84601075ef4b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/powerplantmatching-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.9
    - numpy
    - scipy
    - pandas >=0.24.0
    - networkx >=1.10
    - pycountry
    - country_converter
    - xlrd
    - seaborn
    - pyyaml >=5.1.0
    - requests
    - matplotlib-base
    - geopy
    - unidecode
    - entsoe-py >=0.3.1
    - deprecation
    - tqdm
    - openpyxl

test:
  imports:
    - powerplantmatching
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyPSA/powerplantmatching
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Toolset for generating and managing Power Plant Data
  description: |
    This package provides ready-to-use power plant data for the European
    power system. Starting from openly available power plant datasets,
    the package cleans, standardizes and merges the input data to create
    a new combining dataset, which includes all the important information.
    The package allows to easily update the combined data as
    soon as new input datasets are released.
  doc_url: https://github.com/PyPSA/powerplantmatching
  dev_url: https://github.com/PyPSA/powerplantmatching

extra:
  recipe-maintainers:
    - lkstrp
    - FabianHofmann
    - coroa
    - davide-f
